In [2]:
pip install numpy==1.19.3

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [5]:
a = np.array((1,2,3,4))
a

array([1, 2, 3, 4])

In [6]:
a.shape

(4,)

In [7]:
a.ndim

1

In [8]:
a.size

4

In [9]:
a.dtype

dtype('int32')

In [10]:
int32Range = [-int(2**32/2),int(2**32/2)]
int32Range

[-2147483648, 2147483648]

In [11]:
b = np.array([[1.,2.],[3.,4.]])
b

array([[1., 2.],
       [3., 4.]])

In [12]:
b.size

4

In [13]:
b.shape

(2, 2)

In [14]:
b[:,0]

array([1., 3.])

In [15]:
b[:,1]

array([2., 4.])

In [16]:
np.array([0,4,4],dtype=complex)

array([0.+0.j, 4.+0.j, 4.+0.j])

In [17]:
a = np.empty((3,3))
a

array([[0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 6.067e-321],
       [0.000e+000, 0.000e+000, 0.000e+000]])

In [18]:
a.dtype

dtype('float64')

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
b

array([[1., 2.],
       [3., 4.]])

In [21]:
np.zeros_like(b)

array([[0., 0.],
       [0., 0.]])

In [22]:
np.ones_like(b)

array([[1., 1.],
       [1., 1.]])

In [23]:
for a in np.arange(7):
    print(a)

0
1
2
3
4
5
6


In [24]:
np.arange(20,40,2)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [25]:
np.arange(40,20,-2)

array([40, 38, 36, 34, 32, 30, 28, 26, 24, 22])

In [26]:
np.linspace(20,40,6)

array([20., 24., 28., 32., 36., 40.])

In [27]:
np.arange(3,18,3)

array([ 3,  6,  9, 12, 15])

In [28]:
np.linspace(3,18,6)

array([ 3.,  6.,  9., 12., 15., 18.])

In [29]:
a = np.linspace(3,20,45)

In [30]:
a[1]-a[0]

0.38636363636363624

In [31]:
x,dx = np.linspace(0.,2*np.pi, 100, retstep=True)
dx

0.06346651825433926

In [32]:
def f(i,j):
    return 2*i*j
np.fromfunction(f,(4,3))

array([[ 0.,  0.,  0.],
       [ 0.,  2.,  4.],
       [ 0.,  4.,  8.],
       [ 0.,  6., 12.]])

In [33]:
f = lambda x: x**2-3*x+2
f(1.5)

-0.25

In [34]:
np.fromfunction(lambda i,j: 2*i*j, (4,3)) 

array([[ 0.,  0.,  0.],
       [ 0.,  2.,  4.],
       [ 0.,  4.,  8.],
       [ 0.,  6., 12.]])

In [35]:
arr = np.array([1,2,3,4],dtype='f8')
arr.dtype

dtype('float64')

In [36]:
a.astype('float32')

array([ 3.       ,  3.3863637,  3.7727273,  4.159091 ,  4.5454545,
        4.931818 ,  5.318182 ,  5.7045455,  6.090909 ,  6.4772725,
        6.8636365,  7.25     ,  7.6363635,  8.022727 ,  8.409091 ,
        8.795455 ,  9.181818 ,  9.568182 ,  9.954545 , 10.340909 ,
       10.727273 , 11.113636 , 11.5      , 11.886364 , 12.272727 ,
       12.659091 , 13.045455 , 13.431818 , 13.818182 , 14.204545 ,
       14.590909 , 14.977273 , 15.363636 , 15.75     , 16.136364 ,
       16.522728 , 16.90909  , 17.295454 , 17.681818 , 18.068182 ,
       18.454546 , 18.84091  , 19.227272 , 19.613636 , 20.       ],
      dtype=float32)

In [37]:
a=np.array([[1,2],[3,4]])
b=np.array([[11,12],[13,14]])
a*b

array([[11, 24],
       [39, 56]])

In [38]:
a*a*a

array([[ 1,  8],
       [27, 64]])

In [39]:
a**3

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [40]:
a

array([[1, 2],
       [3, 4]])

In [42]:
a=np.fromfunction(lambda i,j: 2*i*j, (6,6))
a

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  4.,  6.,  8., 10.],
       [ 0.,  4.,  8., 12., 16., 20.],
       [ 0.,  6., 12., 18., 24., 30.],
       [ 0.,  8., 16., 24., 32., 40.],
       [ 0., 10., 20., 30., 40., 50.]])

In [43]:
a[a>10]=60
a

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  4.,  6.,  8., 10.],
       [ 0.,  4.,  8., 60., 60., 60.],
       [ 0.,  6., 60., 60., 60., 60.],
       [ 0.,  8., 60., 60., 60., 60.],
       [ 0., 10., 60., 60., 60., 60.]])

In [44]:
a[a>10]=a[a>10]*10
a

array([[  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   2.,   4.,   6.,   8.,  10.],
       [  0.,   4.,   8., 600., 600., 600.],
       [  0.,   6., 600., 600., 600., 600.],
       [  0.,   8., 600., 600., 600., 600.],
       [  0.,  10., 600., 600., 600., 600.]])

In [46]:
a=np.fromfunction(lambda i,j: 2*i*j, (6,6))
a

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  4.,  6.,  8., 10.],
       [ 0.,  4.,  8., 12., 16., 20.],
       [ 0.,  6., 12., 18., 24., 30.],
       [ 0.,  8., 16., 24., 32., 40.],
       [ 0., 10., 20., 30., 40., 50.]])

In [47]:
a[a>10]=a[a>10]*10
a

array([[  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   2.,   4.,   6.,   8.,  10.],
       [  0.,   4.,   8., 120., 160., 200.],
       [  0.,   6., 120., 180., 240., 300.],
       [  0.,   8., 160., 240., 320., 400.],
       [  0.,  10., 200., 300., 400., 500.]])

In [49]:
a[(a>10)&(a<200)]

array([120., 160., 120., 180., 160.])

In [50]:
np.isnan(a)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [53]:
a[3,3]=np.nan
a

array([[  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   2.,   4.,   6.,   8.,  10.],
       [  0.,   4.,   8., 120., 160., 200.],
       [  0.,   6., 120.,  nan, 240., 300.],
       [  0.,   8., 160., 240., 320., 400.],
       [  0.,  10., 200., 300., 400., 500.]])

In [54]:
np.isnan(a)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [56]:
a=np.fromfunction(lambda i,j: 2*i*j, (6,6))
a

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  4.,  6.,  8., 10.],
       [ 0.,  4.,  8., 12., 16., 20.],
       [ 0.,  6., 12., 18., 24., 30.],
       [ 0.,  8., 16., 24., 32., 40.],
       [ 0., 10., 20., 30., 40., 50.]])

In [57]:
a.flatten()

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  4.,  6.,  8., 10.,  0.,
        4.,  8., 12., 16., 20.,  0.,  6., 12., 18., 24., 30.,  0.,  8.,
       16., 24., 32., 40.,  0., 10., 20., 30., 40., 50.])

In [58]:
a.shape

(6, 6)

In [59]:
b.shape

(2, 2)

In [60]:
b.flatten()

array([11, 12, 13, 14])

In [61]:
b.shape

(2, 2)

In [63]:
b = a.flatten()
b

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  4.,  6.,  8., 10.,  0.,
        4.,  8., 12., 16., 20.,  0.,  6., 12., 18., 24., 30.,  0.,  8.,
       16., 24., 32., 40.,  0., 10., 20., 30., 40., 50.])

In [64]:
b.shape

(36,)

In [66]:
c=a.ravel()
c

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  4.,  6.,  8., 10.,  0.,
        4.,  8., 12., 16., 20.,  0.,  6., 12., 18., 24., 30.,  0.,  8.,
       16., 24., 32., 40.,  0., 10., 20., 30., 40., 50.])

In [68]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
b=np.vstack([a1,a2])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [69]:
c=np.hstack([a1,a2])
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
d=np.dstack([a1,a2])
d

array([[[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]]])

In [72]:
np.dstack?

Signature: np.dstack(tup)
Docstring:
Stack arrays in sequence depth wise (along third axis).

This is equivalent to concatenation along the third axis after 2-D arrays
of shape `(M,N)` have been reshaped to `(M,N,1)` and 1-D arrays of shape
`(N,)` have been reshaped to `(1,N,1)`. Rebuilds arrays divided by
`dsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

Parameters
----------
tup : sequence of arrays
    The arrays must have the same shape along all but the third axis.
    1-D or 2-D arrays must have the same shape.

Returns
-------
stacked : ndarray
    The array formed by stacking the given arrays, will be at least 3-D.

See Also
--------
concatenate : Join a sequence of arrays along an existing axis.
stack : Join a sequence of arrays alo